server {
    server_name bonanza.robio-ai.com www.bonanza.robio-ai.com 216.128.158.136 _;

    client_max_body_size 50m;

    location /static/ {
        alias /root/bonanza/inventario_bonanza/staticfiles/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        return 404;
    }

    location /media-minio/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bonanza.robio-ai.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bonanza.robio-ai.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = bonanza.robio-ai.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name bonanza.robio-ai.com www.bonanza.robio-ai.com 216.128.158.136 _;
    return 404; # managed by Certbot


}
