# Generated by Django 5.2.12 on 2026-03-26 00:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('area_visita', models.CharField(max_length=100)),
                ('autorizado_por', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Salida')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('medico', 'Médico'), ('rh', 'Recursos Humanos'), ('operador', 'Operador'), ('admin_mina', 'Administrador Mina'), ('admin_molino', 'Administrador Molino'), ('seguridad_fisica', 'Seguridad Física'), ('tecnico_seguridad', 'Técnico de Seguridad')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a la Empresa')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_personal/', verbose_name='Fotografía')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto de Emergencia')),
                ('medical_checkup', models.BooleanField(default=False, verbose_name='Revisión Médica Completada')),
                ('medical_comment', models.TextField(blank=True, null=True, verbose_name='Comentario Médico')),
                ('last_checkup_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PermisoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='gestion_personal.person')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de revisión')),
                ('comments', models.TextField(verbose_name='Observaciones médicas')),
                ('is_post_vacation', models.BooleanField(default=False, verbose_name='Control post-vacaciones')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_checks', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='gestion_personal.person')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('presion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_consultations', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_consultations', to='gestion_personal.person')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EPPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_epp', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_assignments', to='gestion_personal.person')),
            ],
            options={
                'verbose_name': 'Asignación de EPP',
                'verbose_name_plural': 'Asignaciones de EPP',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10, verbose_name='Tipo de Registro')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de ingreso/salida')),
                ('reason', models.CharField(blank=True, choices=[('permiso', 'Permiso'), ('traslado', 'Traslado a otro campamento'), ('reunion', 'Reunión'), ('vacaciones', 'Vacaciones')], max_length=20, null=True, verbose_name='Razón')),
                ('campamento_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campamento Destino')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='gestion_personal.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('impuesta_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='gestion_personal.person')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
            },
        ),
        migrations.CreateModel(
            name='VacationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('medical_checkup_done', models.BooleanField(default=False, verbose_name='Control Médico Completado')),
                ('medical_checkup_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Control Médico')),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='Notas Médicas')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_records', to='gestion_personal.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Registro de Vacaciones',
                'verbose_name_plural': 'Registros de Vacaciones',
            },
        ),
        migrations.CreateModel(
            name='VehicleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa del Vehículo')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_conducidos', to='gestion_personal.person')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Vehículo',
                'verbose_name_plural': 'Registros de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='VehiclePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personal.person')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='gestion_personal.vehiclerecord')),
            ],
            options={
                'verbose_name': 'Pasajero de Vehículo',
                'verbose_name_plural': 'Pasajeros de Vehículos',
            },
        ),
        migrations.CreateModel(
            name='VisitaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Visitante')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Número de Identificación')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la Visita')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('hora_programada', models.TimeField(verbose_name='Hora Programada')),
                ('area_visita', models.CharField(max_length=100, verbose_name='Área a Visitar')),
                ('autorizado_por', models.CharField(max_length=100, verbose_name='Autorizado Por')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('programado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_programadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita Programada',
                'verbose_name_plural': 'Visitas Programadas',
                'ordering': ['fecha_programada', 'hora_programada'],
            },
        ),
    ]
