# Generated by Django 5.2 on 2026-06-01 01:30

import gestion_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0002_rrhh_person_control_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=gestion_personal.models.person_photo_upload_to, verbose_name='Fotografía'),
        ),
    ]
