# Generated by Django 5.2 on 2026-06-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0003_alter_person_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Identificador')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('global_admin', 'Administrador Global'), ('medico', 'Médico'), ('rh', 'Recursos Humanos'), ('operador', 'Operador'), ('admin_mina', 'Administrador Mina'), ('admin_molino', 'Administrador Molino'), ('seguridad_fisica', 'Seguridad Física'), ('tecnico_seguridad', 'Técnico de Seguridad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='gestion_personal.organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='gestion_personal.organization', verbose_name='Organización'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('organization', 'id_number'), name='unique_person_id_per_organization'),
        ),
    ]
