# Generated by Django 5.2 on 2026-06-01 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0004_organization_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dias_jornada',
            field=models.PositiveIntegerField(default=22, verbose_name='Días de jornada'),
        ),
        migrations.AddField(
            model_name='person',
            name='observaciones_jornada',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de jornada'),
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='chofer_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del chofer'),
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='chofer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del chofer'),
        ),
        migrations.AddField(
            model_name='vehiclerecord',
            name='salida_registrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_exits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehiclerecord',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_conducidos', to='gestion_personal.person'),
        ),
    ]
