# Generated by Django 5.2 on 2026-06-02 16:16

import gestion_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0005_person_dias_jornada_person_observaciones_jornada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='renuncia_pdf',
            field=models.FileField(blank=True, null=True, upload_to=gestion_personal.models.resignation_pdf_upload_to, verbose_name='PDF de renuncia'),
        ),
    ]
