# Generated by Django 5.2 on 2026-06-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0007_vehiclerecord_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['timestamp'], name='attendance_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['person', 'timestamp'], name='attendance_person_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['record_type', 'timestamp'], name='attendance_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'id_number'], name='person_org_id_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organization', 'estado'], name='person_org_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='person_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerecord',
            index=models.Index(fields=['organization', 'fecha_ingreso'], name='vehicle_org_in_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerecord',
            index=models.Index(fields=['organization', 'fecha_salida'], name='vehicle_org_out_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclerecord',
            index=models.Index(fields=['chofer_cedula'], name='vehicle_driver_id_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorrecord',
            index=models.Index(fields=['fecha'], name='visitor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorrecord',
            index=models.Index(fields=['cedula'], name='visitor_id_idx'),
        ),
    ]
