# Generated by Django 5.2 on 2026-06-04 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0008_attendancerecord_attendance_time_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('worked', 'Trabajó'), ('free', 'Día libre'), ('vacation', 'Vacaciones anuales'), ('permission', 'Permiso'), ('absent', 'No trabajó'), ('late_return', 'Regresó tarde')], max_length=20, verbose_name='Estado')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_work_days', to='gestion_personal.person', verbose_name='Persona')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_workday_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Control mensual de jornada',
                'verbose_name_plural': 'Controles mensuales de jornada',
                'indexes': [models.Index(fields=['date'], name='workday_date_idx'), models.Index(fields=['person', 'date'], name='workday_person_date_idx'), models.Index(fields=['status', 'date'], name='workday_status_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('person', 'date'), name='unique_monthly_workday_per_person_date')],
            },
        ),
    ]
