# Generated by Django 5.2 on 2026-06-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0009_monthlyworkday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateLookupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('propietario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Propietario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=200, null=True)),
                ('anio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Año')),
                ('pais_fabricacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='País de fabricación')),
                ('clase', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('uso', models.CharField(blank=True, max_length=100, null=True)),
                ('color_1', models.CharField(blank=True, max_length=80, null=True)),
                ('color_2', models.CharField(blank=True, max_length=80, null=True)),
                ('carroceria', models.CharField(blank=True, max_length=100, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('vin', models.CharField(blank=True, max_length=80, null=True)),
                ('motor', models.CharField(blank=True, max_length=80, null=True)),
                ('placa_anterior', models.CharField(blank=True, max_length=40, null=True)),
                ('canton_matricula', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimiento_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inspeccion', models.CharField(blank=True, max_length=50, null=True)),
                ('ultimo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindraje', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=80, null=True)),
                ('camv_cpn', models.CharField(blank=True, max_length=80, null=True)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('fecha_compraventa', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_ultima_revision', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_revision_desde', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_revision_hasta', models.CharField(blank=True, max_length=50, null=True)),
                ('tramites', models.JSONField(blank=True, default=list)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('consultas_ecuador_data', models.JSONField(blank=True, default=dict)),
                ('atm_guayaquil_data', models.JSONField(blank=True, default=dict)),
                ('axis_crv_data', models.JSONField(blank=True, default=dict)),
                ('source_errors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_lookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Placa',
                'verbose_name_plural': 'Consultas de Placas',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['placa'], name='plate_lookup_plate_idx'), models.Index(fields=['updated_at'], name='plate_lookup_updated_idx')],
            },
        ),
    ]
