# Generated by Django 5.2 on 2026-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0010_platelookuprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='platelookuprecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consulta finalizada'),
        ),
        migrations.AddField(
            model_name='platelookuprecord',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='Último error'),
        ),
        migrations.AddField(
            model_name='platelookuprecord',
            name='lookup_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Consultando'), ('completed', 'Completada'), ('completed_with_errors', 'Completada con errores'), ('failed', 'Fallida')], default='completed', max_length=30, verbose_name='Estado de consulta'),
        ),
        migrations.AddField(
            model_name='platelookuprecord',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consulta solicitada'),
        ),
        migrations.AddField(
            model_name='platelookuprecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consulta iniciada'),
        ),
    ]
