# Generated by Django 5.2 on 2026-06-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0011_platelookuprecord_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platelookuprecord',
            name='placa_aliases',
            field=models.JSONField(blank=True, default=list, verbose_name='Alias de placa'),
        ),
        migrations.AddField(
            model_name='platelookuprecord',
            name='source_attempts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
