# Generated by Django 5.2 on 2026-06-08 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0012_platelookuprecord_placa_aliases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLookupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('lookup_status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Consultando'), ('completed', 'Completada'), ('completed_with_errors', 'Completada con errores'), ('failed', 'Fallida')], default='pending', max_length=30, verbose_name='Estado de consulta')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Último error')),
                ('nombre_completo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre completo')),
                ('procesos_actor_total', models.PositiveIntegerField(default=0, verbose_name='Procesos como actor')),
                ('procesos_demandado_total', models.PositiveIntegerField(default=0, verbose_name='Procesos como demandado')),
                ('citaciones_total', models.PositiveIntegerField(default=0, verbose_name='Citaciones ANT')),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('funcion_judicial_data', models.JSONField(blank=True, default=dict)),
                ('sri_data', models.JSONField(blank=True, default=dict)),
                ('ant_data', models.JSONField(blank=True, default=dict)),
                ('source_errors', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Consulta solicitada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Consulta iniciada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consulta finalizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_lookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta de Persona',
                'verbose_name_plural': 'Consultas de Personas',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cedula'], name='person_lookup_id_idx'), models.Index(fields=['updated_at'], name='person_lookup_updated_idx')],
            },
        ),
    ]
