# Generated by Django 5.2 on 2026-08-22 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0013_personlookuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del comedor')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_halls', to='gestion_personal.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Comedor',
                'verbose_name_plural': 'Comedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=80, verbose_name='Bloque')),
                ('house', models.CharField(blank=True, max_length=80, verbose_name='Casa')),
                ('number', models.CharField(max_length=30, verbose_name='Número de habitación')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Capacidad total')),
                ('service_status', models.CharField(choices=[('available', 'Disponible'), ('out_of_service', 'Fuera de servicio')], default='available', max_length=20, verbose_name='Estado operativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='gestion_personal.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['block', 'house', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reservada'), ('occupied', 'Ocupada')], default='occupied', max_length=12, verbose_name='Estado')),
                ('check_in_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso')),
                ('notes', models.TextField(blank=True, verbose_name='Novedades')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dining_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='gestion_personal.dininghall', verbose_name='Comedor asignado')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to='gestion_personal.person', verbose_name='Colaborador')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gestion_personal.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Asignación de habitación',
                'verbose_name_plural': 'Asignaciones de habitaciones',
                'ordering': ['room', 'person__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Novedad o requerimiento')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En proceso'), ('resolved', 'Resuelta')], default='pending', max_length=15, verbose_name='Estado')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reportada')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='gestion_personal.room', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Novedad de mantenimiento',
                'verbose_name_plural': 'Novedades de mantenimiento',
                'ordering': ['status', '-reported_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dininghall',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_dining_hall_per_org'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('organization', 'block', 'house', 'number'), name='unique_room_per_org'),
        ),
    ]
