# Generated by Django 5.2 on 2026-08-22 03:05

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_dining_assignments(apps, schema_editor):
    RoomAssignment = apps.get_model('gestion_personal', 'RoomAssignment')
    Person = apps.get_model('gestion_personal', 'Person')
    for person_id, dining_hall_id in RoomAssignment.objects.exclude(
        dining_hall_id=None
    ).values_list('person_id', 'dining_hall_id').iterator():
        Person.objects.filter(pk=person_id).update(dining_hall_id=dining_hall_id)


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0014_dininghall_room_roomassignment_roommaintenanceissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dining_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diners', to='gestion_personal.dininghall', verbose_name='Comedor asignado'),
        ),
        migrations.RunPython(copy_existing_dining_assignments, migrations.RunPython.noop),
    ]
