# Generated by Django 5.2 on 2026-08-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personal', '0016_room_camp_roomassignment_bed_label_annualactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomoccupancymovement',
            name='room_label',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='roomoccupancymovement',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupancy_movements', to='gestion_personal.room'),
        ),
    ]
